### ISSUE TITLE
To run my own videos error

### ISSUE THREAD

**Issue by zdwong** [imatge-upc/rvos#10]
I use this command to run my own video: python demo.py -model_name one-shot-model-davis -frames_path path-to-your-frames --zero_shot --overlay_masks

Howerver, it appears an error: 
![image](https://user-images.githubusercontent.com/3873891/57749419-91c06d00-7710-11e9-957b-c9f9c8c00fa5.png)

**Comment by agirbau** [comment]
I think you are using a one-shot model (which requires an initial input mask) and using a zer-shot configuration. Try using zero-shot-model-davis and check if the problem persists.

**Comment by agirbau** [comment]
Btw pull to the lastest version to to run it.

**Comment by coolbrain** [comment]
I have use the latest version: git clone https://github.com/imatge-upc/rvos.git. If I use zero-shot-model-davis, the problems still exists.

**Comment by agirbau** [comment]
Can you copy and paste your cmd output here?

**Comment by coolbrain** [comment]
The same problem.

**Comment by agirbau** [comment]
Copy and paste your command line prompt in next comment and I'll check :)

**Comment by coolbrain** [comment]
ok, wait for a while.  I have to reconfigure the running environment again. @agirbau  I can make sure that the problem is the same.

**Comment by coolbrain** [comment]
When I run the command again,  it doesn't show the error now. But the video has no segmentation result.
 
python demo.py -model_name  zero-shot-model-davis  -frames_path  /detection/data/ch00011_frames  --zero_shot --overlay_masks

![image](https://user-images.githubusercontent.com/3873891/57964913-2cb68280-796f-11e9-8b6c-bba1549064d0.png)

When I run the comand of this: python demo.py -model_name one-shot-model-davis --overlay_masks
, it has the segmentation result.  @agirbau

**Comment by agirbau** [comment]
That's weird. Can you double check that you don't have the results in models/zero-shot-model-davis/results?

**Comment by coolbrain** [comment]
The  path has the result. But every frame doesn't have the segmentation result. I have check two times. @agirbau

**Comment by coolbrain** [comment]
I run the DAVIS video again, but it has no segmentation result too.
![image](https://user-images.githubusercontent.com/3873891/57971400-1684e280-79c0-11e9-9747-02ac5edb6938.png)
The result picture:
![image](https://user-images.githubusercontent.com/3873891/57971405-2b617600-79c0-11e9-80dd-a02c5f8edb6a.png)

if I run the command: python demo.py -model_name one-shot-model-davis --overlay_masks
The result picture:
![image](https://user-images.githubusercontent.com/3873891/57971422-6663a980-79c0-11e9-9b0d-d6864fda66b2.png)

**Comment by agirbau** [comment]
I will check next week then!

**Comment by agirbau** [comment]
Ok, do a pull and check it again.

**Comment by zdwong** [comment]
Yeah, I have tried the new version, there is no error now. But the performance cannot meet my expectation.

**Comment by carlesventura** [comment]
As you can see in the Tables of the paper the model proposed works much better in the one-shot (or semi-supervised) scenario than in the zero-shot (or unsupervised) scenario. We are working to improve our results for the zero-shot case.

**Comment by zdwong** [comment]
Thanks for your great work trying to do zero-shot(or unsupervised) scenario. I think it's an valuable and interesting research topic. @agilmor  @carlesventura

**Comment by melvin0kuo** [comment]
where can find demo.py？didnt find it ：（
