### ISSUE TITLE
 Figure 2 in paper does not match with code ? Or I misunderstood

### ISSUE THREAD

**Issue by jiangerxiaozhao** [imatge-upc/rvos#12]
Please pay attention to the red box in the figure.

![figure2](https://user-images.githubusercontent.com/38741724/58027239-ca19de00-7b4a-11e9-8688-5468287b0dbf.png)
https://github.com/imatge-upc/rvos/blob/f8f8b1039bf2808b7d22fdb050b2f06ac6a5b172/src/args.py#L106
https://github.com/imatge-upc/rvos/blob/f8f8b1039bf2808b7d22fdb050b2f06ac6a5b172/src/modules/model.py#L45
https://github.com/imatge-upc/rvos/blob/f8f8b1039bf2808b7d22fdb050b2f06ac6a5b172/src/modules/model.py#L46

**Comment by ZhiQue930716** [comment]
I found you are right, the data of size of layers do not match the paper where expressed.  Did you successfully run train?

**Comment by carlesventura** [comment]
We have already changed the figure in the paper from ArXiv: https://arxiv.org/abs/1903.05612

Sorry for the inconvenience.
