### ISSUE TITLE
How do you evaluate the performance for one-shot on DAVIS-2017?

### ISSUE THREAD

**Issue by 815961618** [imatge-upc/rvos#2]
Hi, I am really interested in your work. I notice that in Table 4 of your paper, both J and F of OSNM are much lower than those reported in OSMN (37.7 vs 52.5 for J mean, 44.9 vs 57.1 for F mean). I wonder whether these "J" and "F" in your Table 4 mean "J mean" and "F mean".  If yes, why are they so much lower than these reported in original paper? 
The fowllowing are results on DAVIS-2017 from your paper and OSMN.
### Your results:
![图片](https://user-images.githubusercontent.com/17945632/54587129-1ddc4e00-4a5a-11e9-8d10-b6d059c4cd0a.png)
### OSMN results:
![图片](https://user-images.githubusercontent.com/17945632/54586922-65aea580-4a59-11e9-917a-0be0df03ca4f.png)

**Comment by carlesventura** [comment]
The reason is that the results reported on OSMN paper are on DAVIS 2017 validation set whereas the results we report for OSMN in our paper are on DAVIS 2017 test-dev set. You can find these values on the DAVIS 2017 benchmark website:

https://davischallenge.org/davis2017/soa_compare.html

**Comment by 815961618** [comment]
OK, thank you so much.
