### ISSUE TITLE
ran the train script but nothing happened

### ISSUE THREAD

**Issue by sklf** [imatge-upc/rvos#20]
Hello, I cloned your code and tried to train the model. But after I ran the script, nothing happened. My terminal just showed two messages. So what's the problem?
![image](https://user-images.githubusercontent.com/22724048/65007938-35798e00-d93a-11e9-974d-4b1d8ed58206.png)

**Comment by sklf** [comment]
I fixed this issue. Maybe I didn't download both datasets.

**Comment by XiaoAHeng** [comment]
> I fixed this issue. Maybe I didn't download both datasets.

I also met the question, Do I have to download these two databases?
Thanks in advance!

**Comment by sklf** [comment]
> > I fixed this issue. Maybe I didn't download both datasets.
> 
> I also met the question, Do I have to download these two databases?
> Thanks in advance!
Yeah, you can try to download both datasets. And make sure your GPU is empty for the training process.

**Comment by Yiyiyimu** [comment]
@sklf should I download all those 60+GB dataset of Youtube-VOC? Is there any part of it that we do not need to use when training? Thanks in advance!

**Comment by sklf** [comment]
> @sklf should I download all those 60+GB dataset of Youtube-VOC? Is there any part of it that we do not need to use when training? Thanks in advance!

No, you only need to download the basic dataset ( the smaller one in the google drive). Because only basic dataset has annotations.

**Comment by Yiyiyimu** [comment]
> > @sklf should I download all those 60+GB dataset of Youtube-VOC? Is there any part of it that we do not need to use when training? Thanks in advance!
> 
> No, you only need to download the basic dataset ( the smaller one in the google drive). Because only basic dataset has annotations.

Thank you! Just to make sure, is the file name 'train.zip'?

**Comment by sklf** [comment]
> > > @sklf should I download all those 60+GB dataset of Youtube-VOC? Is there any part of it that we do not need to use when training? Thanks in advance!
> > 
> > 
> > No, you only need to download the basic dataset ( the smaller one in the google drive). Because only basic dataset has annotations.
> 
> Thank you! Just to make sure, is the file name 'train.zip'?

train.zip and valid.zip

**Comment by Yiyiyimu** [comment]
> > > > @sklf should I download all those 60+GB dataset of Youtube-VOC? Is there any part of it that we do not need to use when training? Thanks in advance!
> > > 
> > > 
> > > No, you only need to download the basic dataset ( the smaller one in the google drive). Because only basic dataset has annotations.
> > 
> > 
> > Thank you! Just to make sure, is the file name 'train.zip'?
> 
> train.zip and valid.zip

Thanks!

**Comment by XiaoAHeng** [comment]
> > > I fixed this issue. Maybe I didn't download both datasets.
> > 
> > 
> > I also met the question, Do I have to download these two databases?
> > Thanks in advance!
> 
> Yeah, you can try to download both datasets. And make sure your GPU is empty for the training process.

After solver thr error ,I also met an UnboundLocalError: local variable 'seq_name' referenced before assignment in the dataset.py file, I carefuully browse the file, the variable is not assigned.  What dose the variable mean? Have you encountered a similar problem?
