### ISSUE TITLE
encoder.pt

### ISSUE THREAD

**Issue by molefeskymleya** [imatge-upc/rvos#27]

**Comment by molefeskymleya** [comment]
hello there, enjoyed reading your paper, now trying to run the code. I got the following error:

`[root@c5f5 src]# python3 demo.py -model_name one-shot-model-davis --overlay_masks
[WARNING][28-11-2019 08:22:46] Temporal stability not available
Results will be saved to: ../models/one-shot-model-davis/results/bear
Loading model: one-shot-model-davis
Traceback (most recent call last):
  File "demo.py", line 268, in <module>
    model = Model(args)
  File "demo.py", line 125, in __init__
    self._init_model(args)
  File "demo.py", line 129, in _init_model
    encoder_dict, decoder_dict, _, _, load_args = load_checkpoint(args.model_name, args.use_gpu)
  File "/home/jinweiqi_wangjianming_cs/rvos/rvos/src/utils/utils.py", line 112, in load_checkpoint
    encoder_dict = torch.load(os.path.join('../models',model_name,'encoder.pt'))
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 301, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '../models/one-shot-model-davis/encoder.pt'
[root@c5f5 src]#
`

What is `encoder.pt` and how can I get or generate it?

**Comment by carlesventura** [comment]
You need to download the pre-trained models. You will find them at the end of the documentation.

**Comment by molefeskymleya** [comment]
let me try to do that stat! Thank you!!

**Comment by molefeskymleya** [comment]
it worked, thank you so much. I have closed this issue
