### ISSUE TITLE
How to display visualization results ？

### ISSUE THREAD

**Issue by iris0329** [imatge-upc/rvos#3]
I have run the `eval_previous_mask.py` of one-shot-model-davis model, but how to display visualization results, such as **mask** or something?
I figure out in the `/rvos/src/args.py` there are some args about **visualization and logging**, how to use them ?
Thanks for your help !

**Comment by carlesventura** [comment]
I suppose that you have downloaded the one-shot-model-davis and you have extract this zip file into a folder named one-shot-model-davis within the models folder. 

If you have run ```eval_previous_mask.py``` with the default parameters as given in the scripts, a new folder within the one-shot-model-davis folder should be created containing the binary masks predicted for the different object instances and the different frames. 

If you want a more fancy visualization, like the ones included in the paper, then you can use the flag --overlay_masks so another folder will be also created with the RGB images and the masks with some transparency over it.

**Comment by iris0329** [comment]
Yes, I have downloaded the 'one-shot-model-davis' model and extract it in the right place.

and I use the following parameters:
```
-model_name=one-shot-model-davis
-dataset=davis2017
-eval_split=val
-batch_size=1
-length_clip=130
-gpu_id=0
--overlay_masks
--visdom
--log_ter
```
then it surely create 2 folders as following, but these 2 folders are both empty
![image](https://user-images.githubusercontent.com/26380036/55067147-28ca5a80-50ba-11e9-82f7-66a1e9b32e17.png)

Seems wierd. Thanks for your help !

**Comment by carlesventura** [comment]
Your output in the terminal should be like the one that I attach in this message. 

![one-shot-davis-output](https://user-images.githubusercontent.com/7792351/55068690-b38f6300-5082-11e9-9372-24f268d1ccc1.png)

You should see the frame names for each sequence while they are processed. If it is not the case, I would say that you should check the DAVIS dataloader or the LMDB generator (see dataset_lmdb_generator.py).

I hope it helps!

**Comment by iris0329** [comment]
Thanks for help.
I found the problem is I downloaded another version DAVIS2017
after change `-eval_split=val` to `-eval_split=test-dev`, it works !
Thank you !
