### ISSUE TITLE
lmdb.Error: xxx/lmdb_seq: Function not implemented

### ISSUE THREAD

**Issue by dwqy11** [imatge-upc/rvos#5]
Hi, when I run ' python dataset_lmdb_generator.py -dataset=youtube ', I encountered the following error(when dataset is DAVIS2017, the same error showed up as well.)
How can I fix it?

`
Traceback (most recent call last):
  File "dataset_lmdb_generator.py", line 38, in <module>
    frame_lmdb_generator_sequences.generate_lmdb_file(cfg.PATH.DATA, cfg.PATH.SEQUENCES_TRAIN)
  File "dataset_lmdb_generator.py", line 16, in generate_lmdb_file
    env = lmdb.open(os.path.join(root_dir, 'lmdb_' + self.gen_type))
lmdb.Error: /userhome/rvos/databases/YouTubeVOS/lmdb_seq: Function not implemented
`

**Comment by carlesventura** [comment]
Hi, I think that the problem is that you have the databases folder inside the rvos folder, but they shoud be in the same directory level. In other words, you should have the databases folder in /userhome/databases/ since you have rvos in /userhome/rvos/.

**Comment by dwqy11** [comment]
Thanks！ I‘ve fixed it. Actually I had the databases folder in /userhome with rvos folder in the same level.  However I found that the data folder structure must like the following:
```/userhome/databases/YouTubeVOS/train/JPEGImages```
And then the error is gone.

In a word, this error should be resulted by "cannot find the data files".
