### ISSUE TITLE
Where can I see the metrics after running evaluation?

### ISSUE THREAD

**Issue by Linardos** [imatge-upc/rvos#7]
I followed the guidelines and it seems I successfully managed to run the evaluation:
```
python ../src/eval_previous_mask.py -model_name=one-shot-model-davis -dataset=davis2017 -eval_split=test-dev -batch_size=1 -length_clip=130 -gpu_id=0
[WARNING][16-04-2019 17:50:13] Temporal stability not available
Eval logs will be saved to: ../models/one-shot-model-davis/eval.log
```

The eval log displays the following message:
![image](https://user-images.githubusercontent.com/26694607/56244224-103fd580-60a5-11e9-898c-ad91db0d5f80.png)

I am not sure where I can see the metrics though.

**Comment by carlesventura** [comment]
The evaluation script generates the segmentation masks for the sequences of the chosen dataset, but it does not give any evaluation measure. All the experiments have been evaluated using the official evaluation server from either DAVIS or YouTube-VOS. For the training of the model, a loss based on the Jaccard measure has been used.
