### ISSUE TITLE
Woud you like to share evaluating code on YoutubeVOS?

### ISSUE THREAD

**Issue by LiangTinting** [imatge-upc/rvos#8]
Hi, thank you for sharing your work! The idea is great and the code is elegantly written.
I have evaluated RVOS results on DAVIS validation set with DAVIS-2017 official evaluation code. But the YoutubeVOS dataset structure is quite different from DAVIS, would you like to share the evaluation code? Thank you for your time.

**Comment by carlesventura** [comment]
I'm sorry but we haven't implemented the evaluation scripts. We have generated the masks and these have been always evaluated in the official evaluation server, from either DAVIS or YouTube-VOS. However, you can implement it based on the evaluation code available in DAVIS in Matlab and Python in the following website: https://davischallenge.org/davis2017/code.html

**Comment by XiaoAHeng** [comment]
> Hi, thank you for sharing your work! The idea is great and the code is elegantly written.
> I have evaluated RVOS results on DAVIS validation set with DAVIS-2017 official evaluation code. But the YoutubeVOS dataset structure is quite different from DAVIS, would you like to share the evaluation code? Thank you for your time.



> I'm sorry but we haven't implemented the evaluation scripts. We have generated the masks and these have been always evaluated in the official evaluation server, from either DAVIS or YouTube-VOS. However, you can implement it based on the evaluation code available in DAVIS in Matlab and Python in the following website: https://davischallenge.org/davis2017/code.html

Which version of the Youtube-VOS dataset  is used , 2018 version or 2019 version?

**Comment by XiaoAHeng** [comment]
> Hi, thank you for sharing your work! The idea is great and the code is elegantly written.
> I have evaluated RVOS results on DAVIS validation set with DAVIS-2017 official evaluation code. But the YoutubeVOS dataset structure is quite different from DAVIS, would you like to share the evaluation code? Thank you for your time.

Which version of the Youtube-VOS dataset is used , 2018 version or 2019 version?

**Comment by LiangTinting** [comment]
> validation

I used Youtube-VOS 2018 version

**Comment by LiangTinting** [comment]
> > Hi, thank you for sharing your work! The idea is great and the code is elegantly written.
> > I have evaluated RVOS results on DAVIS validation set with DAVIS-2017 official evaluation code. But the YoutubeVOS dataset structure is quite different from DAVIS, would you like to share the evaluation code? Thank you for your time.
> 
> Which version of the Youtube-VOS dataset is used , 2018 version or 2019 version?

Youtube-VOS 2018 version.

**Comment by XiaoAHeng** [comment]
> > > Hi, thank you for sharing your work! The idea is great and the code is elegantly written.
> > > I have evaluated RVOS results on DAVIS validation set with DAVIS-2017 official evaluation code. But the YoutubeVOS dataset structure is quite different from DAVIS, would you like to share the evaluation code? Thank you for your time.
> > 
> > 
> > Which version of the Youtube-VOS dataset is used , 2018 version or 2019 version?
> 
> Youtube-VOS 2018 version.

Thnak you!
