### ISSUE TITLE
How to get the J and F values of segmentation results？

### ISSUE THREAD

**Issue by wobujiaoluoxaiohei** [imatge-upc/rvos#9]
Hi,thank you for sharing the source code.
By running eval.py and eval_previous_mask.py , I have obtained the RGB image of the segmentation result.
I have found the evaluation.py in the rvos\src\dataloader  folder ，I want to know how I can get the J and F values of the results.
Thanks for your help !

**Comment by carlesventura** [comment]
I'm sorry but we haven't implemented the evaluation scripts. We have generated the masks and these have been always evaluated in the official evaluation server, from either DAVIS or YouTube-VOS. However, you can implement it based on the evaluation code available in DAVIS in Matlab and Python in the following website: https://davischallenge.org/davis2017/code.html
If you want to use the official evaluation servers, you need to use the code ```src/prepare_results_submission.py```(for YouTube-VOS) or ```src/prepare_results_submission_davis.py```for DAVIS, which generates a folder that once compressed can be sent to the evaluation servers.

**Comment by wobujiaoluoxaiohei** [comment]
I see. Thank you very much for your reply.
